baseURL = "https://poligonija.github.io/"
LanguageCode = "sl-SI"
Title = "Poligonija"

[permalinks]
    scifi = "/scifi/:title/"

[params]

    [[params.heading]]
    title = "Transhumanizem"
    url = "/transhuman"

    [[params.heading]]
    title = "Umetnost in tehnologija"
    url = "/art"

    [[params.heading]]
    title = "Znanstvena fantastika"
    url = "/events"


