baseURL = "https://poligonija.org/"
LanguageCode = "sl-SI"
Title = "Poligonija"

[permalinks]
    scifi = "/scifi/:title/"

[params]

    [[params.heading]]
    title = "Umetnost in tehnologija"
    url = "/"

    [[params.heading]]
    title = "SCI-FI in konec prihodnosti"
    url = "/1"


